Support Drupal 11 SQLite version.

diff --git a/src/Dockerfile b/src/Dockerfile
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -39,6 +39,16 @@ RUN curl https://awscli.amazonaws.com/awscli-exe-linux-"$(uname -m)".zip -o "aws
 RUN wget https://github.com/mikefarah/yq/releases/download/v4.21.1/yq_linux_"$(dpkg --print-architecture)".tar.gz -O - |\
   tar xz && mv yq_linux_"$(dpkg --print-architecture)" /usr/bin/yq
 
+# Upgrade SQLite for Drupal 11 testing.
+# @see https://www.drupal.org/project/drupal/issues/3346338
+# @see https://github.com/docksal/service-cli/pull/327/files
+RUN set -xe; \
+  echo "deb https://deb.debian.org/debian testing main" | tee /etc/apt/sources.list.d/testing.list; \
+  apt-get update >/dev/null; \
+  apt-get install -y -t testing sqlite3;\
+  # Cleanup
+  apt-get clean; rm -rf /var/lib/apt/lists/*
+
 # Install expect, vim
 RUN apt-get clean && \
   apt update && \
